    -- O insert abaixo cadastra o aluno manualmente na tabela MATRICULA
    INSERT MATRICULA (MATRICULA, CURSO, MATERIA,PROFESSOR,PERLETIVO)
    VALUES (1,'ENG','BDA',1,2025)

    INSERT MATRICULA (MATRICULA, CURSO, MATERIA,PROFESSOR,PERLETIVO)
    VALUES (1,'ENG','PRG',2,2025)

